### PR TITLE
Adjustments for ODT redesign branch.

### PR DESCRIPTION
**Pull request by LarsGit223**
This are adjustment to make the columns plugin work with the ODT plugins redesign branch.
Please check and merge.

### CODE REVIEW

**Comment by dwp-forge** [comment]
Thanks for the patch. Generally it looks okay, but to my taste it's somewhat too intrusive. Would you mind to rework it a bit to minimize changes to the existing code? I would suggest to:
- Rename existing ODT-related methods to someOdtMethodNameV1 (e.g. addOdtTableStyleV1)
- Put new implementation into methods named someOdtMethodNameV2
  - Preferably put all V2 methods in a single block of code after V1, so you have one big addition instead of multiple small ones.
- Create function variables for each of the version-specific methods and initialize them properly.
  - Rename is_new_odt to odtInitialized (BTW, use camelCase for members and init them in the constructor) and wrap function variables initialization into a method. The code at the start of ODT rendering branch should read: "if not odtInitialized then initializeOdt()"
  - Optionally remove is_new_odt entirely and call initializeOdt() from the constructor. I don't think there will be too much of a performance penalty if this is done for XHTML renderer as well. But I don't have a strong opinion either way.

**Comment by LarsGit223** [comment]
Hmmm...will think about that.

Maybe it would be the easiest to create two little classes for the two versions of ODT export and let them implement an interface or extend a base class.
Then at the start of rendering create an object of the class required (V1 or V2) and later call that methods from that object. So we only need one pointer to an object and not multiple function variables.

What do you think?

**Comment by dwp-forge** [comment]
That's even better. It somewhat lacks on the "intrusiveness" part, with moving all that code around, but results in much cleaner design. And clean design is always a winner :)

**Comment by LarsGit223** [comment]
So I changed it now, please have a look. As you mentioned this changes a lot of the previous code also. But the main render function looks very clean now.

**Comment by dwp-forge** [comment]
I did some coding style clean-up and minor refactoring of your patch. But contributing to someone else's pull request seems to be a [PITA](http://stackoverflow.com/questions/15191350/contributing-to-an-existing-pull-request) on GitHub. I pushed my changes to the head of your pull request, so it should be possible to get them with `git fetch dwp-forge pull/4/head:redesign-updated`. If that does not work for you, I guess, the easiest would be just to merge your pull request and proceed from there.

I tested the plugin with current release of ODT plugin. It looks like it's still v1. At least I had v1 renderer crashing (fixed that as well). Did not test v2, so I would appreciate if you could verify once more that I did not break anything and v2 renderer is okay.

**Comment by LarsGit223** [comment]
I will do that tomorrow (if I got time for it).

Yes, the actual release is still v1. v2 is for the upcoming release and for now will only be used if you install the redesign branch of the ODT plugin. A lot of plugins had to be adjusted, see https://github.com/LarsGit223/dokuwiki-plugin-odt/wiki/dokuwiki-plugin-redesign-adj if you like.

**Comment by LarsGit223** [comment]
Looks good and worked well with v2 after a minor fix.

**Comment by dwp-forge** [comment]
Merged from command line.

**Comment by LarsGit223** [comment]
Thanks!

**Pull request closed without merging**
